ENGINE_PATH = ENGINE_PATH or "engine"

local engine = {}
engine.system = require(ENGINE_PATH.."/system")
engine.animation = require(ENGINE_PATH.."/animation")
engine.thread = require(ENGINE_PATH.."/thread")
engine.serialize = require(ENGINE_PATH.."/serialize")
engine.layer = require(ENGINE_PATH.."/layer")
engine.layerTile = require(ENGINE_PATH.."/layerTile")
engine.scriptLayer = require(ENGINE_PATH.."/scriptLayer")
engine.sourceImage = require(ENGINE_PATH.."/sourceImage")
engine.sourceTileset = require(ENGINE_PATH.."/sourceTileset")
engine.sourceSpritesheet = require(ENGINE_PATH.."/sourceSpritesheet")
engine.sourcePolyline = require(ENGINE_PATH.."/sourcePolyline")
engine.sourceFont = require(ENGINE_PATH.."/sourceFont")
engine.sourceRectangle = require(ENGINE_PATH.."/sourceRectangle")
engine.sourceCircle = require(ENGINE_PATH.."/sourceCircle")
engine.sourceMesh = require(ENGINE_PATH.."/sourceMesh")
engine.sourceParticleSystem = require(ENGINE_PATH.."/sourceParticleSystem")
engine.sourceSpritefont = require(ENGINE_PATH.."/sourceSpritefont")
engine.sourceSpritebatch = require(ENGINE_PATH.."/sourceSpritebatch")
engine.image = require(ENGINE_PATH.."/image")
engine.animationSheet = require(ENGINE_PATH.."/animationSheet")
engine.grid = require(ENGINE_PATH.."/grid")
engine.asset = require(ENGINE_PATH.."/asset")
engine.camera = require(ENGINE_PATH.."/camera")
engine.sprite = require(ENGINE_PATH.."/sprite")
engine.geometry = require(ENGINE_PATH.."/geometry")
engine.textinput = require(ENGINE_PATH.."/textinput")
engine.scene = require(ENGINE_PATH.."/scene")
engine.event = require(ENGINE_PATH.."/event")
engine.tween = require(ENGINE_PATH.."/tween")
engine.data = require(ENGINE_PATH.."/data")
engine.input = require(ENGINE_PATH.."/input")
engine.path = require(ENGINE_PATH.."/path")

engine.system.registerCallbacks()
return engine